### ISSUE TITLE
Use r-edited_development and r-edited_test names for databases

### ISSUE THREAD

**Issue by pavels-gaimovics** [ErnestsEida/R-edited#30]
1. It is convention to use this name
2. About tests database. Each time tests run, they clear all data from db. So if you have same name for development and test like now, you will lost all your development data.
3. You can use shorhand for default data. This is yaml feature. Like this:

```
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: r-edited_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: r-edited_test
  username: postgres
  password: postgres
```
